export { DependencyGraph } from "./graph.js";
export type { GraphNode, GraphEdge, ImpactResult, NodeKind, EdgeKind } from "./graph-types.js";
export { scanProject } from "./scanner.js";
export type { ScanResult } from "./scanner.js";
export { parseFile, getParseWarnings, clearParseWarnings } from "./parser.js";
export type { ParseResult, ParseWarning } from "./parser-types.js";
export { extractDependencies } from "./extractor.js";
export type { ExtractionResult, ExtractorContext } from "./extractor.js";
export { analyzeProject, updateFile, getFileImpact } from "./analyzer.js";
export type { AnalysisStats, FullAnalysis } from "./analyzer.js";
export { loadTsConfigAliases } from "./tsconfig.js";
export type { PathAlias, TsConfigInfo } from "./tsconfig.js";
export { analyzeHealth } from "./health.js";
export type { HealthReport } from "./health.js";
export { loadConfig } from "./config.js";
export type { BoundaryRule } from "./config-types.js";
export { checkBoundaries } from "./boundaries.js";
export { analyzeHotspots } from "./hotspots.js";
export type { HotspotRisk } from "./hotspots.js";
export { loadEnvFiles, analyzeEnv } from "./env.js";
export { findTestTargets, getChangedFiles, isTestFile } from "./test-targets.js";
export type { TestTarget, TestTargetReport } from "./test-targets.js";
export { analyzeCoupling } from "./coupling.js";
export type { CouplingPair, CouplingReport, CouplingKind } from "./coupling.js";
export { focusFile } from "./focus.js";
export type { FocusReport, FocusExport } from "./focus.js";
export { exportGraph } from "./export-graph.js";
export type { ExportFormat } from "./export-graph.js";
export { analyzeSafeDelete } from "./safe-delete.js";
export type { SafeDeleteReport, SafetyVerdict } from "./safe-delete.js";
export { analyzeComplexity, computeFileComplexity, buildComplexityReport } from "./complexity.js";
export type { ComplexityReport, FileComplexity, FunctionComplexity, ComplexityRisk } from "./complexity.js";
export { analyzeRisk } from "./risk.js";
export type { RiskReport, FileRisk, RiskLevel } from "./risk.js";
export { planDeadExportRemovals, applyRefactorPlan } from "./refactor.js";
export type { RefactorPlan, RefactorAction, RefactorResult } from "./refactor.js";
export { runPlugins, discoverPlugins } from "./plugins.js";
export type { PluginContext, PluginViolation, PluginResult, ImpulsePlugin, AllPluginsResult } from "./plugins.js";
export { runReview, runQuickReview, computeVerdict } from "./review.js";
export type { ReviewOptions, ReviewReport, ReviewVerdict, FileReview, VerdictLevel, QuickReviewCache } from "./review.js";
