export { DependencyGraph } from "./graph.js";
export type { GraphNode, GraphEdge, ImpactResult, NodeKind, EdgeKind } from "./graph-types.js";
export { scanProject } from "./scanner.js";
export type { ScanResult } from "./scanner.js";
export { parseFile, getParseWarnings, clearParseWarnings } from "./parser.js";
export type { ParseResult, ParseWarning } from "./parser-types.js";
export { extractDependencies } from "./extractor.js";
export type { ExtractionResult, ExtractorContext } from "./extractor.js";
export { analyzeProject, updateFile, getFileImpact } from "./analyzer.js";
export type { AnalysisStats, FullAnalysis } from "./analyzer.js";
export { loadTsConfigAliases } from "./tsconfig.js";
export type { PathAlias, TsConfigInfo } from "./tsconfig.js";
export { analyzeHealth } from "./health.js";
export type { HealthReport } from "./health.js";
export { loadConfig } from "./config.js";
export type { BoundaryRule } from "./config-types.js";
export { checkBoundaries } from "./boundaries.js";
export { analyzeHotspots } from "./hotspots.js";
export type { HotspotRisk } from "./hotspots.js";
export { loadEnvFiles, analyzeEnv } from "./env.js";
export { findTestTargets, getChangedFiles, isTestFile } from "./test-targets.js";
export type { TestTarget, TestTargetReport } from "./test-targets.js";
export { analyzeCoupling } from "./coupling.js";
export type { CouplingPair, CouplingReport, CouplingKind } from "./coupling.js";
